// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7k325tffg676-2,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.374114,HLS_SYN_LAT=2864,HLS_SYN_TPT=1275,HLS_SYN_MEM=0,HLS_SYN_DSP=12,HLS_SYN_FF=43024,HLS_SYN_LUT=35970,HLS_VERSION=2018_2}" *)

module mlp (
        ap_clk,
        ap_rst,
        weights_L1_0_V_address0,
        weights_L1_0_V_ce0,
        weights_L1_0_V_d0,
        weights_L1_0_V_q0,
        weights_L1_0_V_we0,
        weights_L1_0_V_address1,
        weights_L1_0_V_ce1,
        weights_L1_0_V_d1,
        weights_L1_0_V_q1,
        weights_L1_0_V_we1,
        weights_L1_1_V_address0,
        weights_L1_1_V_ce0,
        weights_L1_1_V_d0,
        weights_L1_1_V_q0,
        weights_L1_1_V_we0,
        weights_L1_1_V_address1,
        weights_L1_1_V_ce1,
        weights_L1_1_V_d1,
        weights_L1_1_V_q1,
        weights_L1_1_V_we1,
        weights_L1_2_V_address0,
        weights_L1_2_V_ce0,
        weights_L1_2_V_d0,
        weights_L1_2_V_q0,
        weights_L1_2_V_we0,
        weights_L1_2_V_address1,
        weights_L1_2_V_ce1,
        weights_L1_2_V_d1,
        weights_L1_2_V_q1,
        weights_L1_2_V_we1,
        weights_L1_3_V_address0,
        weights_L1_3_V_ce0,
        weights_L1_3_V_d0,
        weights_L1_3_V_q0,
        weights_L1_3_V_we0,
        weights_L1_3_V_address1,
        weights_L1_3_V_ce1,
        weights_L1_3_V_d1,
        weights_L1_3_V_q1,
        weights_L1_3_V_we1,
        weights_L1_4_V_address0,
        weights_L1_4_V_ce0,
        weights_L1_4_V_d0,
        weights_L1_4_V_q0,
        weights_L1_4_V_we0,
        weights_L1_4_V_address1,
        weights_L1_4_V_ce1,
        weights_L1_4_V_d1,
        weights_L1_4_V_q1,
        weights_L1_4_V_we1,
        weights_L1_5_V_address0,
        weights_L1_5_V_ce0,
        weights_L1_5_V_d0,
        weights_L1_5_V_q0,
        weights_L1_5_V_we0,
        weights_L1_5_V_address1,
        weights_L1_5_V_ce1,
        weights_L1_5_V_d1,
        weights_L1_5_V_q1,
        weights_L1_5_V_we1,
        weights_L1_6_V_address0,
        weights_L1_6_V_ce0,
        weights_L1_6_V_d0,
        weights_L1_6_V_q0,
        weights_L1_6_V_we0,
        weights_L1_6_V_address1,
        weights_L1_6_V_ce1,
        weights_L1_6_V_d1,
        weights_L1_6_V_q1,
        weights_L1_6_V_we1,
        weights_L1_7_V_address0,
        weights_L1_7_V_ce0,
        weights_L1_7_V_d0,
        weights_L1_7_V_q0,
        weights_L1_7_V_we0,
        weights_L1_7_V_address1,
        weights_L1_7_V_ce1,
        weights_L1_7_V_d1,
        weights_L1_7_V_q1,
        weights_L1_7_V_we1,
        weights_L2_V_address0,
        weights_L2_V_ce0,
        weights_L2_V_d0,
        weights_L2_V_q0,
        weights_L2_V_we0,
        weights_L2_V_address1,
        weights_L2_V_ce1,
        weights_L2_V_d1,
        weights_L2_V_q1,
        weights_L2_V_we1,
        input_0_V_address0,
        input_0_V_ce0,
        input_0_V_d0,
        input_0_V_q0,
        input_0_V_we0,
        input_0_V_address1,
        input_0_V_ce1,
        input_0_V_d1,
        input_0_V_q1,
        input_0_V_we1,
        input_1_V_address0,
        input_1_V_ce0,
        input_1_V_d0,
        input_1_V_q0,
        input_1_V_we0,
        input_1_V_address1,
        input_1_V_ce1,
        input_1_V_d1,
        input_1_V_q1,
        input_1_V_we1,
        input_2_V_address0,
        input_2_V_ce0,
        input_2_V_d0,
        input_2_V_q0,
        input_2_V_we0,
        input_2_V_address1,
        input_2_V_ce1,
        input_2_V_d1,
        input_2_V_q1,
        input_2_V_we1,
        input_3_V_address0,
        input_3_V_ce0,
        input_3_V_d0,
        input_3_V_q0,
        input_3_V_we0,
        input_3_V_address1,
        input_3_V_ce1,
        input_3_V_d1,
        input_3_V_q1,
        input_3_V_we1,
        input_4_V_address0,
        input_4_V_ce0,
        input_4_V_d0,
        input_4_V_q0,
        input_4_V_we0,
        input_4_V_address1,
        input_4_V_ce1,
        input_4_V_d1,
        input_4_V_q1,
        input_4_V_we1,
        input_5_V_address0,
        input_5_V_ce0,
        input_5_V_d0,
        input_5_V_q0,
        input_5_V_we0,
        input_5_V_address1,
        input_5_V_ce1,
        input_5_V_d1,
        input_5_V_q1,
        input_5_V_we1,
        input_6_V_address0,
        input_6_V_ce0,
        input_6_V_d0,
        input_6_V_q0,
        input_6_V_we0,
        input_6_V_address1,
        input_6_V_ce1,
        input_6_V_d1,
        input_6_V_q1,
        input_6_V_we1,
        input_7_V_address0,
        input_7_V_ce0,
        input_7_V_d0,
        input_7_V_q0,
        input_7_V_we0,
        input_7_V_address1,
        input_7_V_ce1,
        input_7_V_d1,
        input_7_V_q1,
        input_7_V_we1,
        ap_return,
        ap_done,
        ap_start,
        ap_ready,
        ap_idle
);


input   ap_clk;
input   ap_rst;
output  [10:0] weights_L1_0_V_address0;
output   weights_L1_0_V_ce0;
output  [17:0] weights_L1_0_V_d0;
input  [17:0] weights_L1_0_V_q0;
output   weights_L1_0_V_we0;
output  [10:0] weights_L1_0_V_address1;
output   weights_L1_0_V_ce1;
output  [17:0] weights_L1_0_V_d1;
input  [17:0] weights_L1_0_V_q1;
output   weights_L1_0_V_we1;
output  [10:0] weights_L1_1_V_address0;
output   weights_L1_1_V_ce0;
output  [17:0] weights_L1_1_V_d0;
input  [17:0] weights_L1_1_V_q0;
output   weights_L1_1_V_we0;
output  [10:0] weights_L1_1_V_address1;
output   weights_L1_1_V_ce1;
output  [17:0] weights_L1_1_V_d1;
input  [17:0] weights_L1_1_V_q1;
output   weights_L1_1_V_we1;
output  [10:0] weights_L1_2_V_address0;
output   weights_L1_2_V_ce0;
output  [17:0] weights_L1_2_V_d0;
input  [17:0] weights_L1_2_V_q0;
output   weights_L1_2_V_we0;
output  [10:0] weights_L1_2_V_address1;
output   weights_L1_2_V_ce1;
output  [17:0] weights_L1_2_V_d1;
input  [17:0] weights_L1_2_V_q1;
output   weights_L1_2_V_we1;
output  [10:0] weights_L1_3_V_address0;
output   weights_L1_3_V_ce0;
output  [17:0] weights_L1_3_V_d0;
input  [17:0] weights_L1_3_V_q0;
output   weights_L1_3_V_we0;
output  [10:0] weights_L1_3_V_address1;
output   weights_L1_3_V_ce1;
output  [17:0] weights_L1_3_V_d1;
input  [17:0] weights_L1_3_V_q1;
output   weights_L1_3_V_we1;
output  [10:0] weights_L1_4_V_address0;
output   weights_L1_4_V_ce0;
output  [17:0] weights_L1_4_V_d0;
input  [17:0] weights_L1_4_V_q0;
output   weights_L1_4_V_we0;
output  [10:0] weights_L1_4_V_address1;
output   weights_L1_4_V_ce1;
output  [17:0] weights_L1_4_V_d1;
input  [17:0] weights_L1_4_V_q1;
output   weights_L1_4_V_we1;
output  [10:0] weights_L1_5_V_address0;
output   weights_L1_5_V_ce0;
output  [17:0] weights_L1_5_V_d0;
input  [17:0] weights_L1_5_V_q0;
output   weights_L1_5_V_we0;
output  [10:0] weights_L1_5_V_address1;
output   weights_L1_5_V_ce1;
output  [17:0] weights_L1_5_V_d1;
input  [17:0] weights_L1_5_V_q1;
output   weights_L1_5_V_we1;
output  [10:0] weights_L1_6_V_address0;
output   weights_L1_6_V_ce0;
output  [17:0] weights_L1_6_V_d0;
input  [17:0] weights_L1_6_V_q0;
output   weights_L1_6_V_we0;
output  [10:0] weights_L1_6_V_address1;
output   weights_L1_6_V_ce1;
output  [17:0] weights_L1_6_V_d1;
input  [17:0] weights_L1_6_V_q1;
output   weights_L1_6_V_we1;
output  [10:0] weights_L1_7_V_address0;
output   weights_L1_7_V_ce0;
output  [17:0] weights_L1_7_V_d0;
input  [17:0] weights_L1_7_V_q0;
output   weights_L1_7_V_we0;
output  [10:0] weights_L1_7_V_address1;
output   weights_L1_7_V_ce1;
output  [17:0] weights_L1_7_V_d1;
input  [17:0] weights_L1_7_V_q1;
output   weights_L1_7_V_we1;
output  [8:0] weights_L2_V_address0;
output   weights_L2_V_ce0;
output  [17:0] weights_L2_V_d0;
input  [17:0] weights_L2_V_q0;
output   weights_L2_V_we0;
output  [8:0] weights_L2_V_address1;
output   weights_L2_V_ce1;
output  [17:0] weights_L2_V_d1;
input  [17:0] weights_L2_V_q1;
output   weights_L2_V_we1;
output  [5:0] input_0_V_address0;
output   input_0_V_ce0;
output  [17:0] input_0_V_d0;
input  [17:0] input_0_V_q0;
output   input_0_V_we0;
output  [5:0] input_0_V_address1;
output   input_0_V_ce1;
output  [17:0] input_0_V_d1;
input  [17:0] input_0_V_q1;
output   input_0_V_we1;
output  [5:0] input_1_V_address0;
output   input_1_V_ce0;
output  [17:0] input_1_V_d0;
input  [17:0] input_1_V_q0;
output   input_1_V_we0;
output  [5:0] input_1_V_address1;
output   input_1_V_ce1;
output  [17:0] input_1_V_d1;
input  [17:0] input_1_V_q1;
output   input_1_V_we1;
output  [5:0] input_2_V_address0;
output   input_2_V_ce0;
output  [17:0] input_2_V_d0;
input  [17:0] input_2_V_q0;
output   input_2_V_we0;
output  [5:0] input_2_V_address1;
output   input_2_V_ce1;
output  [17:0] input_2_V_d1;
input  [17:0] input_2_V_q1;
output   input_2_V_we1;
output  [5:0] input_3_V_address0;
output   input_3_V_ce0;
output  [17:0] input_3_V_d0;
input  [17:0] input_3_V_q0;
output   input_3_V_we0;
output  [5:0] input_3_V_address1;
output   input_3_V_ce1;
output  [17:0] input_3_V_d1;
input  [17:0] input_3_V_q1;
output   input_3_V_we1;
output  [5:0] input_4_V_address0;
output   input_4_V_ce0;
output  [17:0] input_4_V_d0;
input  [17:0] input_4_V_q0;
output   input_4_V_we0;
output  [5:0] input_4_V_address1;
output   input_4_V_ce1;
output  [17:0] input_4_V_d1;
input  [17:0] input_4_V_q1;
output   input_4_V_we1;
output  [5:0] input_5_V_address0;
output   input_5_V_ce0;
output  [17:0] input_5_V_d0;
input  [17:0] input_5_V_q0;
output   input_5_V_we0;
output  [5:0] input_5_V_address1;
output   input_5_V_ce1;
output  [17:0] input_5_V_d1;
input  [17:0] input_5_V_q1;
output   input_5_V_we1;
output  [5:0] input_6_V_address0;
output   input_6_V_ce0;
output  [17:0] input_6_V_d0;
input  [17:0] input_6_V_q0;
output   input_6_V_we0;
output  [5:0] input_6_V_address1;
output   input_6_V_ce1;
output  [17:0] input_6_V_d1;
input  [17:0] input_6_V_q1;
output   input_6_V_we1;
output  [5:0] input_7_V_address0;
output   input_7_V_ce0;
output  [17:0] input_7_V_d0;
input  [17:0] input_7_V_q0;
output   input_7_V_we0;
output  [5:0] input_7_V_address1;
output   input_7_V_ce1;
output  [17:0] input_7_V_d1;
input  [17:0] input_7_V_q1;
output   input_7_V_we1;
output  [31:0] ap_return;
output   ap_done;
input   ap_start;
output   ap_ready;
output   ap_idle;

wire   [17:0] bias_added_0_V_i_q0;
wire   [17:0] bias_added_0_V_i_q1;
wire   [17:0] bias_added_0_V_t_q0;
wire   [17:0] bias_added_0_V_t_q1;
wire   [17:0] bias_added_1_V_i_q0;
wire   [17:0] bias_added_1_V_i_q1;
wire   [17:0] bias_added_1_V_t_q0;
wire   [17:0] bias_added_1_V_t_q1;
wire   [17:0] bias_added_2_V_i_q0;
wire   [17:0] bias_added_2_V_i_q1;
wire   [17:0] bias_added_2_V_t_q0;
wire   [17:0] bias_added_2_V_t_q1;
wire   [17:0] bias_added_3_V_i_q0;
wire   [17:0] bias_added_3_V_i_q1;
wire   [17:0] bias_added_3_V_t_q0;
wire   [17:0] bias_added_3_V_t_q1;
wire   [17:0] bias_added_4_V_i_q0;
wire   [17:0] bias_added_4_V_i_q1;
wire   [17:0] bias_added_4_V_t_q0;
wire   [17:0] bias_added_4_V_t_q1;
wire   [17:0] bias_added_5_V_i_q0;
wire   [17:0] bias_added_5_V_i_q1;
wire   [17:0] bias_added_5_V_t_q0;
wire   [17:0] bias_added_5_V_t_q1;
wire   [17:0] bias_added_6_V_i_q0;
wire   [17:0] bias_added_6_V_i_q1;
wire   [17:0] bias_added_6_V_t_q0;
wire   [17:0] bias_added_6_V_t_q1;
wire   [17:0] bias_added_7_V_i_q0;
wire   [17:0] bias_added_7_V_i_q1;
wire   [17:0] bias_added_7_V_t_q0;
wire   [17:0] bias_added_7_V_t_q1;
wire   [17:0] L1_no_activ_V_i_q0;
wire   [17:0] L1_no_activ_V_t_q0;
wire   [17:0] L1_activ_V_i_q0;
wire   [17:0] L1_activ_V_t_q0;
wire   [17:0] L2_bias_added_V_i_q0;
wire   [17:0] L2_bias_added_V_i_q1;
wire   [17:0] L2_bias_added_V_t_q0;
wire   [17:0] L2_bias_added_V_t_q1;
wire   [17:0] L2_out_V_i_q0;
wire   [17:0] L2_out_V_t_q0;
wire   [17:0] L2_out_activ_V_i_q0;
wire   [17:0] L2_out_activ_V_t_q0;
wire    add_bias_pre_L1_U0_ap_start;
wire    add_bias_pre_L1_U0_ap_done;
wire    add_bias_pre_L1_U0_ap_continue;
wire    add_bias_pre_L1_U0_ap_idle;
wire    add_bias_pre_L1_U0_ap_ready;
wire   [5:0] add_bias_pre_L1_U0_input_0_V_address0;
wire    add_bias_pre_L1_U0_input_0_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_input_1_V_address0;
wire    add_bias_pre_L1_U0_input_1_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_input_2_V_address0;
wire    add_bias_pre_L1_U0_input_2_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_input_3_V_address0;
wire    add_bias_pre_L1_U0_input_3_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_input_4_V_address0;
wire    add_bias_pre_L1_U0_input_4_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_input_5_V_address0;
wire    add_bias_pre_L1_U0_input_5_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_input_6_V_address0;
wire    add_bias_pre_L1_U0_input_6_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_input_7_V_address0;
wire    add_bias_pre_L1_U0_input_7_V_ce0;
wire   [5:0] add_bias_pre_L1_U0_result_0_V_address0;
wire    add_bias_pre_L1_U0_result_0_V_ce0;
wire    add_bias_pre_L1_U0_result_0_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_0_V_d0;
wire   [5:0] add_bias_pre_L1_U0_result_1_V_address0;
wire    add_bias_pre_L1_U0_result_1_V_ce0;
wire    add_bias_pre_L1_U0_result_1_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_1_V_d0;
wire   [5:0] add_bias_pre_L1_U0_result_2_V_address0;
wire    add_bias_pre_L1_U0_result_2_V_ce0;
wire    add_bias_pre_L1_U0_result_2_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_2_V_d0;
wire   [5:0] add_bias_pre_L1_U0_result_3_V_address0;
wire    add_bias_pre_L1_U0_result_3_V_ce0;
wire    add_bias_pre_L1_U0_result_3_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_3_V_d0;
wire   [5:0] add_bias_pre_L1_U0_result_4_V_address0;
wire    add_bias_pre_L1_U0_result_4_V_ce0;
wire    add_bias_pre_L1_U0_result_4_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_4_V_d0;
wire   [5:0] add_bias_pre_L1_U0_result_5_V_address0;
wire    add_bias_pre_L1_U0_result_5_V_ce0;
wire    add_bias_pre_L1_U0_result_5_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_5_V_d0;
wire   [5:0] add_bias_pre_L1_U0_result_6_V_address0;
wire    add_bias_pre_L1_U0_result_6_V_ce0;
wire    add_bias_pre_L1_U0_result_6_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_6_V_d0;
wire   [5:0] add_bias_pre_L1_U0_result_7_V_address0;
wire    add_bias_pre_L1_U0_result_7_V_ce0;
wire    add_bias_pre_L1_U0_result_7_V_we0;
wire   [17:0] add_bias_pre_L1_U0_result_7_V_d0;
wire    ap_channel_done_bias_added_7_V;
wire    add_bias_pre_L1_U0_result_7_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_7_V;
wire    ap_sync_channel_write_bias_added_7_V;
wire    ap_channel_done_bias_added_6_V;
wire    add_bias_pre_L1_U0_result_6_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_6_V;
wire    ap_sync_channel_write_bias_added_6_V;
wire    ap_channel_done_bias_added_5_V;
wire    add_bias_pre_L1_U0_result_5_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_5_V;
wire    ap_sync_channel_write_bias_added_5_V;
wire    ap_channel_done_bias_added_4_V;
wire    add_bias_pre_L1_U0_result_4_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_4_V;
wire    ap_sync_channel_write_bias_added_4_V;
wire    ap_channel_done_bias_added_3_V;
wire    add_bias_pre_L1_U0_result_3_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_3_V;
wire    ap_sync_channel_write_bias_added_3_V;
wire    ap_channel_done_bias_added_2_V;
wire    add_bias_pre_L1_U0_result_2_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_2_V;
wire    ap_sync_channel_write_bias_added_2_V;
wire    ap_channel_done_bias_added_1_V;
wire    add_bias_pre_L1_U0_result_1_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_1_V;
wire    ap_sync_channel_write_bias_added_1_V;
wire    ap_channel_done_bias_added_0_V;
wire    add_bias_pre_L1_U0_result_0_V_full_n;
reg    ap_sync_reg_channel_write_bias_added_0_V;
wire    ap_sync_channel_write_bias_added_0_V;
wire    mvprod_layer_1_U0_ap_start;
wire    mvprod_layer_1_U0_ap_done;
wire    mvprod_layer_1_U0_ap_continue;
wire    mvprod_layer_1_U0_ap_idle;
wire    mvprod_layer_1_U0_ap_ready;
wire   [10:0] mvprod_layer_1_U0_matrix_0_V_address0;
wire    mvprod_layer_1_U0_matrix_0_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_0_V_address1;
wire    mvprod_layer_1_U0_matrix_0_V_ce1;
wire   [10:0] mvprod_layer_1_U0_matrix_1_V_address0;
wire    mvprod_layer_1_U0_matrix_1_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_1_V_address1;
wire    mvprod_layer_1_U0_matrix_1_V_ce1;
wire   [10:0] mvprod_layer_1_U0_matrix_2_V_address0;
wire    mvprod_layer_1_U0_matrix_2_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_2_V_address1;
wire    mvprod_layer_1_U0_matrix_2_V_ce1;
wire   [10:0] mvprod_layer_1_U0_matrix_3_V_address0;
wire    mvprod_layer_1_U0_matrix_3_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_3_V_address1;
wire    mvprod_layer_1_U0_matrix_3_V_ce1;
wire   [10:0] mvprod_layer_1_U0_matrix_4_V_address0;
wire    mvprod_layer_1_U0_matrix_4_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_4_V_address1;
wire    mvprod_layer_1_U0_matrix_4_V_ce1;
wire   [10:0] mvprod_layer_1_U0_matrix_5_V_address0;
wire    mvprod_layer_1_U0_matrix_5_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_5_V_address1;
wire    mvprod_layer_1_U0_matrix_5_V_ce1;
wire   [10:0] mvprod_layer_1_U0_matrix_6_V_address0;
wire    mvprod_layer_1_U0_matrix_6_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_6_V_address1;
wire    mvprod_layer_1_U0_matrix_6_V_ce1;
wire   [10:0] mvprod_layer_1_U0_matrix_7_V_address0;
wire    mvprod_layer_1_U0_matrix_7_V_ce0;
wire   [10:0] mvprod_layer_1_U0_matrix_7_V_address1;
wire    mvprod_layer_1_U0_matrix_7_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_0_V_address0;
wire    mvprod_layer_1_U0_input_0_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_0_V_address1;
wire    mvprod_layer_1_U0_input_0_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_1_V_address0;
wire    mvprod_layer_1_U0_input_1_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_1_V_address1;
wire    mvprod_layer_1_U0_input_1_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_2_V_address0;
wire    mvprod_layer_1_U0_input_2_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_2_V_address1;
wire    mvprod_layer_1_U0_input_2_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_3_V_address0;
wire    mvprod_layer_1_U0_input_3_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_3_V_address1;
wire    mvprod_layer_1_U0_input_3_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_4_V_address0;
wire    mvprod_layer_1_U0_input_4_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_4_V_address1;
wire    mvprod_layer_1_U0_input_4_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_5_V_address0;
wire    mvprod_layer_1_U0_input_5_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_5_V_address1;
wire    mvprod_layer_1_U0_input_5_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_6_V_address0;
wire    mvprod_layer_1_U0_input_6_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_6_V_address1;
wire    mvprod_layer_1_U0_input_6_V_ce1;
wire   [5:0] mvprod_layer_1_U0_input_7_V_address0;
wire    mvprod_layer_1_U0_input_7_V_ce0;
wire   [5:0] mvprod_layer_1_U0_input_7_V_address1;
wire    mvprod_layer_1_U0_input_7_V_ce1;
wire   [4:0] mvprod_layer_1_U0_result_V_address0;
wire    mvprod_layer_1_U0_result_V_ce0;
wire    mvprod_layer_1_U0_result_V_we0;
wire   [17:0] mvprod_layer_1_U0_result_V_d0;
wire    ap_channel_done_L1_no_activ_V;
wire    mvprod_layer_1_U0_result_V_full_n;
wire    sigmoid_activation_L_1_U0_ap_start;
wire    sigmoid_activation_L_1_U0_ap_done;
wire    sigmoid_activation_L_1_U0_ap_continue;
wire    sigmoid_activation_L_1_U0_ap_idle;
wire    sigmoid_activation_L_1_U0_ap_ready;
wire   [4:0] sigmoid_activation_L_1_U0_input_V_address0;
wire    sigmoid_activation_L_1_U0_input_V_ce0;
wire   [4:0] sigmoid_activation_L_1_U0_result_V_address0;
wire    sigmoid_activation_L_1_U0_result_V_ce0;
wire    sigmoid_activation_L_1_U0_result_V_we0;
wire   [17:0] sigmoid_activation_L_1_U0_result_V_d0;
wire    ap_channel_done_L1_activ_V;
wire    sigmoid_activation_L_1_U0_result_V_full_n;
wire    add_bias_pre_L2_U0_ap_start;
wire    add_bias_pre_L2_U0_ap_done;
wire    add_bias_pre_L2_U0_ap_continue;
wire    add_bias_pre_L2_U0_ap_idle;
wire    add_bias_pre_L2_U0_ap_ready;
wire   [4:0] add_bias_pre_L2_U0_input_V_address0;
wire    add_bias_pre_L2_U0_input_V_ce0;
wire   [4:0] add_bias_pre_L2_U0_result_V_address0;
wire    add_bias_pre_L2_U0_result_V_ce0;
wire    add_bias_pre_L2_U0_result_V_we0;
wire   [17:0] add_bias_pre_L2_U0_result_V_d0;
wire    ap_channel_done_L2_bias_added_V;
wire    add_bias_pre_L2_U0_result_V_full_n;
wire    mvprod_layer_2_U0_ap_start;
wire    mvprod_layer_2_U0_ap_done;
wire    mvprod_layer_2_U0_ap_continue;
wire    mvprod_layer_2_U0_ap_idle;
wire    mvprod_layer_2_U0_ap_ready;
wire   [8:0] mvprod_layer_2_U0_matrix_V_address0;
wire    mvprod_layer_2_U0_matrix_V_ce0;
wire   [8:0] mvprod_layer_2_U0_matrix_V_address1;
wire    mvprod_layer_2_U0_matrix_V_ce1;
wire   [4:0] mvprod_layer_2_U0_input_V_address0;
wire    mvprod_layer_2_U0_input_V_ce0;
wire   [4:0] mvprod_layer_2_U0_input_V_address1;
wire    mvprod_layer_2_U0_input_V_ce1;
wire   [3:0] mvprod_layer_2_U0_result_V_address0;
wire    mvprod_layer_2_U0_result_V_ce0;
wire    mvprod_layer_2_U0_result_V_we0;
wire   [17:0] mvprod_layer_2_U0_result_V_d0;
wire    ap_channel_done_L2_out_V;
wire    mvprod_layer_2_U0_result_V_full_n;
wire    sigmoid_activation_L_U0_ap_start;
wire    sigmoid_activation_L_U0_ap_done;
wire    sigmoid_activation_L_U0_ap_continue;
wire    sigmoid_activation_L_U0_ap_idle;
wire    sigmoid_activation_L_U0_ap_ready;
wire   [3:0] sigmoid_activation_L_U0_input_V_address0;
wire    sigmoid_activation_L_U0_input_V_ce0;
wire   [3:0] sigmoid_activation_L_U0_result_V_address0;
wire    sigmoid_activation_L_U0_result_V_ce0;
wire    sigmoid_activation_L_U0_result_V_we0;
wire   [17:0] sigmoid_activation_L_U0_result_V_d0;
wire    ap_channel_done_L2_out_activ_V;
wire    sigmoid_activation_L_U0_result_V_full_n;
wire    classify_U0_ap_start;
wire    classify_U0_ap_done;
wire    classify_U0_ap_continue;
wire    classify_U0_ap_idle;
wire    classify_U0_ap_ready;
wire   [3:0] classify_U0_activated_L2_V_address0;
wire    classify_U0_activated_L2_V_ce0;
wire   [31:0] classify_U0_ap_return;
wire    ap_channel_done_digit;
wire    digit_full_n;
wire    Block_arrayctor_loop_U0_ap_start;
wire    Block_arrayctor_loop_U0_ap_done;
wire    Block_arrayctor_loop_U0_ap_continue;
wire    Block_arrayctor_loop_U0_ap_idle;
wire    Block_arrayctor_loop_U0_ap_ready;
wire   [31:0] Block_arrayctor_loop_U0_ap_return;
wire    ap_channel_done_digit_load_loc_chann;
wire    digit_load_loc_chann_full_n;
wire    p_src_mlp_cpp_lin_U0_ap_start;
wire    p_src_mlp_cpp_lin_U0_ap_done;
wire    p_src_mlp_cpp_lin_U0_ap_continue;
wire    p_src_mlp_cpp_lin_U0_ap_idle;
wire    p_src_mlp_cpp_lin_U0_ap_ready;
wire   [31:0] p_src_mlp_cpp_lin_U0_ap_return;
wire   [31:0] tmp_p_src_mlp_cpp_lin_fu_222_ap_return;
wire    ap_sync_continue;
wire    bias_added_0_V_i_full_n;
wire    bias_added_0_V_t_empty_n;
wire   [17:0] bias_added_0_V_t_d1;
wire    bias_added_0_V_t_we1;
wire    bias_added_1_V_i_full_n;
wire    bias_added_1_V_t_empty_n;
wire   [17:0] bias_added_1_V_t_d1;
wire    bias_added_1_V_t_we1;
wire    bias_added_2_V_i_full_n;
wire    bias_added_2_V_t_empty_n;
wire   [17:0] bias_added_2_V_t_d1;
wire    bias_added_2_V_t_we1;
wire    bias_added_3_V_i_full_n;
wire    bias_added_3_V_t_empty_n;
wire   [17:0] bias_added_3_V_t_d1;
wire    bias_added_3_V_t_we1;
wire    bias_added_4_V_i_full_n;
wire    bias_added_4_V_t_empty_n;
wire   [17:0] bias_added_4_V_t_d1;
wire    bias_added_4_V_t_we1;
wire    bias_added_5_V_i_full_n;
wire    bias_added_5_V_t_empty_n;
wire   [17:0] bias_added_5_V_t_d1;
wire    bias_added_5_V_t_we1;
wire    bias_added_6_V_i_full_n;
wire    bias_added_6_V_t_empty_n;
wire   [17:0] bias_added_6_V_t_d1;
wire    bias_added_6_V_t_we1;
wire    bias_added_7_V_i_full_n;
wire    bias_added_7_V_t_empty_n;
wire   [17:0] bias_added_7_V_t_d1;
wire    bias_added_7_V_t_we1;
wire    L1_no_activ_V_i_full_n;
wire    L1_no_activ_V_t_empty_n;
wire    L1_activ_V_i_full_n;
wire    L1_activ_V_t_empty_n;
wire    L2_bias_added_V_i_full_n;
wire    L2_bias_added_V_t_empty_n;
wire   [17:0] L2_bias_added_V_t_d1;
wire    L2_bias_added_V_t_we1;
wire    L2_out_V_i_full_n;
wire    L2_out_V_t_empty_n;
wire    L2_out_activ_V_i_full_n;
wire    L2_out_activ_V_t_empty_n;
wire   [31:0] digit_dout;
wire    digit_empty_n;
wire   [31:0] digit_load_loc_chann_dout;
wire    digit_load_loc_chann_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_mvprod_layer_1_U0_ap_ready;
wire    ap_sync_mvprod_layer_1_U0_ap_ready;
reg   [1:0] mvprod_layer_1_U0_ap_ready_count;
reg    ap_sync_reg_mvprod_layer_2_U0_ap_ready;
wire    ap_sync_mvprod_layer_2_U0_ap_ready;
reg   [1:0] mvprod_layer_2_U0_ap_ready_count;
reg    ap_sync_reg_add_bias_pre_L1_U0_ap_ready;
wire    ap_sync_add_bias_pre_L1_U0_ap_ready;
reg   [1:0] add_bias_pre_L1_U0_ap_ready_count;
wire    add_bias_pre_L1_U0_start_full_n;
wire    add_bias_pre_L1_U0_start_write;
wire    mvprod_layer_1_U0_start_full_n;
wire    mvprod_layer_1_U0_start_write;
wire    sigmoid_activation_L_1_U0_start_full_n;
wire    sigmoid_activation_L_1_U0_start_write;
wire    add_bias_pre_L2_U0_start_full_n;
wire    add_bias_pre_L2_U0_start_write;
wire    mvprod_layer_2_U0_start_full_n;
wire    mvprod_layer_2_U0_start_write;
wire    sigmoid_activation_L_U0_start_full_n;
wire    sigmoid_activation_L_U0_start_write;
wire    classify_U0_start_full_n;
wire    classify_U0_start_write;
wire    Block_arrayctor_loop_U0_start_full_n;
wire    Block_arrayctor_loop_U0_start_write;
wire    p_src_mlp_cpp_lin_U0_start_full_n;
wire    p_src_mlp_cpp_lin_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_bias_added_7_V = 1'b0;
#0 ap_sync_reg_channel_write_bias_added_6_V = 1'b0;
#0 ap_sync_reg_channel_write_bias_added_5_V = 1'b0;
#0 ap_sync_reg_channel_write_bias_added_4_V = 1'b0;
#0 ap_sync_reg_channel_write_bias_added_3_V = 1'b0;
#0 ap_sync_reg_channel_write_bias_added_2_V = 1'b0;
#0 ap_sync_reg_channel_write_bias_added_1_V = 1'b0;
#0 ap_sync_reg_channel_write_bias_added_0_V = 1'b0;
#0 ap_sync_reg_mvprod_layer_1_U0_ap_ready = 1'b0;
#0 mvprod_layer_1_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_mvprod_layer_2_U0_ap_ready = 1'b0;
#0 mvprod_layer_2_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_add_bias_pre_L1_U0_ap_ready = 1'b0;
#0 add_bias_pre_L1_U0_ap_ready_count = 2'd0;
end

mlp_bias_added_0_V #(
    .DataWidth( 18 ),
    .AddressRange( 51 ),
    .AddressWidth( 6 ))
bias_added_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_0_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_0_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_0_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_0_V_d0),
    .i_q0(bias_added_0_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_0_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_0_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_0_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_0_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_0_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_0_V_ce1),
    .t_q1(bias_added_0_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_0_V_i_full_n),
    .i_write(ap_channel_done_bias_added_0_V),
    .t_empty_n(bias_added_0_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_bias_added_0_V #(
    .DataWidth( 18 ),
    .AddressRange( 51 ),
    .AddressWidth( 6 ))
bias_added_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_1_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_1_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_1_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_1_V_d0),
    .i_q0(bias_added_1_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_1_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_1_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_1_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_1_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_1_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_1_V_ce1),
    .t_q1(bias_added_1_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_1_V_i_full_n),
    .i_write(ap_channel_done_bias_added_1_V),
    .t_empty_n(bias_added_1_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_bias_added_0_V #(
    .DataWidth( 18 ),
    .AddressRange( 51 ),
    .AddressWidth( 6 ))
bias_added_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_2_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_2_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_2_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_2_V_d0),
    .i_q0(bias_added_2_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_2_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_2_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_2_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_2_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_2_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_2_V_ce1),
    .t_q1(bias_added_2_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_2_V_i_full_n),
    .i_write(ap_channel_done_bias_added_2_V),
    .t_empty_n(bias_added_2_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_bias_added_0_V #(
    .DataWidth( 18 ),
    .AddressRange( 51 ),
    .AddressWidth( 6 ))
bias_added_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_3_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_3_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_3_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_3_V_d0),
    .i_q0(bias_added_3_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_3_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_3_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_3_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_3_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_3_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_3_V_ce1),
    .t_q1(bias_added_3_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_3_V_i_full_n),
    .i_write(ap_channel_done_bias_added_3_V),
    .t_empty_n(bias_added_3_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_bias_added_0_V #(
    .DataWidth( 18 ),
    .AddressRange( 51 ),
    .AddressWidth( 6 ))
bias_added_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_4_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_4_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_4_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_4_V_d0),
    .i_q0(bias_added_4_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_4_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_4_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_4_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_4_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_4_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_4_V_ce1),
    .t_q1(bias_added_4_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_4_V_i_full_n),
    .i_write(ap_channel_done_bias_added_4_V),
    .t_empty_n(bias_added_4_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_bias_added_0_V #(
    .DataWidth( 18 ),
    .AddressRange( 51 ),
    .AddressWidth( 6 ))
bias_added_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_5_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_5_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_5_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_5_V_d0),
    .i_q0(bias_added_5_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_5_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_5_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_5_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_5_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_5_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_5_V_ce1),
    .t_q1(bias_added_5_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_5_V_i_full_n),
    .i_write(ap_channel_done_bias_added_5_V),
    .t_empty_n(bias_added_5_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_bias_added_0_V #(
    .DataWidth( 18 ),
    .AddressRange( 51 ),
    .AddressWidth( 6 ))
bias_added_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_6_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_6_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_6_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_6_V_d0),
    .i_q0(bias_added_6_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_6_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_6_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_6_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_6_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_6_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_6_V_ce1),
    .t_q1(bias_added_6_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_6_V_i_full_n),
    .i_write(ap_channel_done_bias_added_6_V),
    .t_empty_n(bias_added_6_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_bias_added_7_V #(
    .DataWidth( 18 ),
    .AddressRange( 44 ),
    .AddressWidth( 6 ))
bias_added_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L1_U0_result_7_V_address0),
    .i_ce0(add_bias_pre_L1_U0_result_7_V_ce0),
    .i_we0(add_bias_pre_L1_U0_result_7_V_we0),
    .i_d0(add_bias_pre_L1_U0_result_7_V_d0),
    .i_q0(bias_added_7_V_i_q0),
    .i_address1(6'd0),
    .i_ce1(1'b0),
    .i_q1(bias_added_7_V_i_q1),
    .t_address0(mvprod_layer_1_U0_input_7_V_address0),
    .t_ce0(mvprod_layer_1_U0_input_7_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(bias_added_7_V_t_q0),
    .t_address1(mvprod_layer_1_U0_input_7_V_address1),
    .t_ce1(mvprod_layer_1_U0_input_7_V_ce1),
    .t_q1(bias_added_7_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(bias_added_7_V_i_full_n),
    .i_write(ap_channel_done_bias_added_7_V),
    .t_empty_n(bias_added_7_V_t_empty_n),
    .t_read(mvprod_layer_1_U0_ap_ready)
);

mlp_L1_no_activ_V #(
    .DataWidth( 18 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
L1_no_activ_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(mvprod_layer_1_U0_result_V_address0),
    .i_ce0(mvprod_layer_1_U0_result_V_ce0),
    .i_we0(mvprod_layer_1_U0_result_V_we0),
    .i_d0(mvprod_layer_1_U0_result_V_d0),
    .i_q0(L1_no_activ_V_i_q0),
    .t_address0(sigmoid_activation_L_1_U0_input_V_address0),
    .t_ce0(sigmoid_activation_L_1_U0_input_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(L1_no_activ_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(L1_no_activ_V_i_full_n),
    .i_write(mvprod_layer_1_U0_ap_done),
    .t_empty_n(L1_no_activ_V_t_empty_n),
    .t_read(sigmoid_activation_L_1_U0_ap_ready)
);

mlp_L1_no_activ_V #(
    .DataWidth( 18 ),
    .AddressRange( 25 ),
    .AddressWidth( 5 ))
L1_activ_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(sigmoid_activation_L_1_U0_result_V_address0),
    .i_ce0(sigmoid_activation_L_1_U0_result_V_ce0),
    .i_we0(sigmoid_activation_L_1_U0_result_V_we0),
    .i_d0(sigmoid_activation_L_1_U0_result_V_d0),
    .i_q0(L1_activ_V_i_q0),
    .t_address0(add_bias_pre_L2_U0_input_V_address0),
    .t_ce0(add_bias_pre_L2_U0_input_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(L1_activ_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(L1_activ_V_i_full_n),
    .i_write(sigmoid_activation_L_1_U0_ap_done),
    .t_empty_n(L1_activ_V_t_empty_n),
    .t_read(add_bias_pre_L2_U0_ap_ready)
);

mlp_L2_bias_added_V #(
    .DataWidth( 18 ),
    .AddressRange( 26 ),
    .AddressWidth( 5 ))
L2_bias_added_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(add_bias_pre_L2_U0_result_V_address0),
    .i_ce0(add_bias_pre_L2_U0_result_V_ce0),
    .i_we0(add_bias_pre_L2_U0_result_V_we0),
    .i_d0(add_bias_pre_L2_U0_result_V_d0),
    .i_q0(L2_bias_added_V_i_q0),
    .i_address1(5'd0),
    .i_ce1(1'b0),
    .i_q1(L2_bias_added_V_i_q1),
    .t_address0(mvprod_layer_2_U0_input_V_address0),
    .t_ce0(mvprod_layer_2_U0_input_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(L2_bias_added_V_t_q0),
    .t_address1(mvprod_layer_2_U0_input_V_address1),
    .t_ce1(mvprod_layer_2_U0_input_V_ce1),
    .t_q1(L2_bias_added_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(L2_bias_added_V_i_full_n),
    .i_write(add_bias_pre_L2_U0_ap_done),
    .t_empty_n(L2_bias_added_V_t_empty_n),
    .t_read(mvprod_layer_2_U0_ap_ready)
);

mlp_L2_out_V #(
    .DataWidth( 18 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
L2_out_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(mvprod_layer_2_U0_result_V_address0),
    .i_ce0(mvprod_layer_2_U0_result_V_ce0),
    .i_we0(mvprod_layer_2_U0_result_V_we0),
    .i_d0(mvprod_layer_2_U0_result_V_d0),
    .i_q0(L2_out_V_i_q0),
    .t_address0(sigmoid_activation_L_U0_input_V_address0),
    .t_ce0(sigmoid_activation_L_U0_input_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(L2_out_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(L2_out_V_i_full_n),
    .i_write(mvprod_layer_2_U0_ap_done),
    .t_empty_n(L2_out_V_t_empty_n),
    .t_read(sigmoid_activation_L_U0_ap_ready)
);

mlp_L2_out_V #(
    .DataWidth( 18 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
L2_out_activ_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(sigmoid_activation_L_U0_result_V_address0),
    .i_ce0(sigmoid_activation_L_U0_result_V_ce0),
    .i_we0(sigmoid_activation_L_U0_result_V_we0),
    .i_d0(sigmoid_activation_L_U0_result_V_d0),
    .i_q0(L2_out_activ_V_i_q0),
    .t_address0(classify_U0_activated_L2_V_address0),
    .t_ce0(classify_U0_activated_L2_V_ce0),
    .t_we0(1'b0),
    .t_d0(18'd0),
    .t_q0(L2_out_activ_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(L2_out_activ_V_i_full_n),
    .i_write(sigmoid_activation_L_U0_ap_done),
    .t_empty_n(L2_out_activ_V_t_empty_n),
    .t_read(classify_U0_ap_ready)
);

add_bias_pre_L1 add_bias_pre_L1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(add_bias_pre_L1_U0_ap_start),
    .ap_done(add_bias_pre_L1_U0_ap_done),
    .ap_continue(add_bias_pre_L1_U0_ap_continue),
    .ap_idle(add_bias_pre_L1_U0_ap_idle),
    .ap_ready(add_bias_pre_L1_U0_ap_ready),
    .input_0_V_address0(add_bias_pre_L1_U0_input_0_V_address0),
    .input_0_V_ce0(add_bias_pre_L1_U0_input_0_V_ce0),
    .input_0_V_q0(input_0_V_q0),
    .input_1_V_address0(add_bias_pre_L1_U0_input_1_V_address0),
    .input_1_V_ce0(add_bias_pre_L1_U0_input_1_V_ce0),
    .input_1_V_q0(input_1_V_q0),
    .input_2_V_address0(add_bias_pre_L1_U0_input_2_V_address0),
    .input_2_V_ce0(add_bias_pre_L1_U0_input_2_V_ce0),
    .input_2_V_q0(input_2_V_q0),
    .input_3_V_address0(add_bias_pre_L1_U0_input_3_V_address0),
    .input_3_V_ce0(add_bias_pre_L1_U0_input_3_V_ce0),
    .input_3_V_q0(input_3_V_q0),
    .input_4_V_address0(add_bias_pre_L1_U0_input_4_V_address0),
    .input_4_V_ce0(add_bias_pre_L1_U0_input_4_V_ce0),
    .input_4_V_q0(input_4_V_q0),
    .input_5_V_address0(add_bias_pre_L1_U0_input_5_V_address0),
    .input_5_V_ce0(add_bias_pre_L1_U0_input_5_V_ce0),
    .input_5_V_q0(input_5_V_q0),
    .input_6_V_address0(add_bias_pre_L1_U0_input_6_V_address0),
    .input_6_V_ce0(add_bias_pre_L1_U0_input_6_V_ce0),
    .input_6_V_q0(input_6_V_q0),
    .input_7_V_address0(add_bias_pre_L1_U0_input_7_V_address0),
    .input_7_V_ce0(add_bias_pre_L1_U0_input_7_V_ce0),
    .input_7_V_q0(input_7_V_q0),
    .result_0_V_address0(add_bias_pre_L1_U0_result_0_V_address0),
    .result_0_V_ce0(add_bias_pre_L1_U0_result_0_V_ce0),
    .result_0_V_we0(add_bias_pre_L1_U0_result_0_V_we0),
    .result_0_V_d0(add_bias_pre_L1_U0_result_0_V_d0),
    .result_1_V_address0(add_bias_pre_L1_U0_result_1_V_address0),
    .result_1_V_ce0(add_bias_pre_L1_U0_result_1_V_ce0),
    .result_1_V_we0(add_bias_pre_L1_U0_result_1_V_we0),
    .result_1_V_d0(add_bias_pre_L1_U0_result_1_V_d0),
    .result_2_V_address0(add_bias_pre_L1_U0_result_2_V_address0),
    .result_2_V_ce0(add_bias_pre_L1_U0_result_2_V_ce0),
    .result_2_V_we0(add_bias_pre_L1_U0_result_2_V_we0),
    .result_2_V_d0(add_bias_pre_L1_U0_result_2_V_d0),
    .result_3_V_address0(add_bias_pre_L1_U0_result_3_V_address0),
    .result_3_V_ce0(add_bias_pre_L1_U0_result_3_V_ce0),
    .result_3_V_we0(add_bias_pre_L1_U0_result_3_V_we0),
    .result_3_V_d0(add_bias_pre_L1_U0_result_3_V_d0),
    .result_4_V_address0(add_bias_pre_L1_U0_result_4_V_address0),
    .result_4_V_ce0(add_bias_pre_L1_U0_result_4_V_ce0),
    .result_4_V_we0(add_bias_pre_L1_U0_result_4_V_we0),
    .result_4_V_d0(add_bias_pre_L1_U0_result_4_V_d0),
    .result_5_V_address0(add_bias_pre_L1_U0_result_5_V_address0),
    .result_5_V_ce0(add_bias_pre_L1_U0_result_5_V_ce0),
    .result_5_V_we0(add_bias_pre_L1_U0_result_5_V_we0),
    .result_5_V_d0(add_bias_pre_L1_U0_result_5_V_d0),
    .result_6_V_address0(add_bias_pre_L1_U0_result_6_V_address0),
    .result_6_V_ce0(add_bias_pre_L1_U0_result_6_V_ce0),
    .result_6_V_we0(add_bias_pre_L1_U0_result_6_V_we0),
    .result_6_V_d0(add_bias_pre_L1_U0_result_6_V_d0),
    .result_7_V_address0(add_bias_pre_L1_U0_result_7_V_address0),
    .result_7_V_ce0(add_bias_pre_L1_U0_result_7_V_ce0),
    .result_7_V_we0(add_bias_pre_L1_U0_result_7_V_we0),
    .result_7_V_d0(add_bias_pre_L1_U0_result_7_V_d0)
);

mvprod_layer_1 mvprod_layer_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(mvprod_layer_1_U0_ap_start),
    .ap_done(mvprod_layer_1_U0_ap_done),
    .ap_continue(mvprod_layer_1_U0_ap_continue),
    .ap_idle(mvprod_layer_1_U0_ap_idle),
    .ap_ready(mvprod_layer_1_U0_ap_ready),
    .matrix_0_V_address0(mvprod_layer_1_U0_matrix_0_V_address0),
    .matrix_0_V_ce0(mvprod_layer_1_U0_matrix_0_V_ce0),
    .matrix_0_V_q0(weights_L1_0_V_q0),
    .matrix_0_V_address1(mvprod_layer_1_U0_matrix_0_V_address1),
    .matrix_0_V_ce1(mvprod_layer_1_U0_matrix_0_V_ce1),
    .matrix_0_V_q1(weights_L1_0_V_q1),
    .matrix_1_V_address0(mvprod_layer_1_U0_matrix_1_V_address0),
    .matrix_1_V_ce0(mvprod_layer_1_U0_matrix_1_V_ce0),
    .matrix_1_V_q0(weights_L1_1_V_q0),
    .matrix_1_V_address1(mvprod_layer_1_U0_matrix_1_V_address1),
    .matrix_1_V_ce1(mvprod_layer_1_U0_matrix_1_V_ce1),
    .matrix_1_V_q1(weights_L1_1_V_q1),
    .matrix_2_V_address0(mvprod_layer_1_U0_matrix_2_V_address0),
    .matrix_2_V_ce0(mvprod_layer_1_U0_matrix_2_V_ce0),
    .matrix_2_V_q0(weights_L1_2_V_q0),
    .matrix_2_V_address1(mvprod_layer_1_U0_matrix_2_V_address1),
    .matrix_2_V_ce1(mvprod_layer_1_U0_matrix_2_V_ce1),
    .matrix_2_V_q1(weights_L1_2_V_q1),
    .matrix_3_V_address0(mvprod_layer_1_U0_matrix_3_V_address0),
    .matrix_3_V_ce0(mvprod_layer_1_U0_matrix_3_V_ce0),
    .matrix_3_V_q0(weights_L1_3_V_q0),
    .matrix_3_V_address1(mvprod_layer_1_U0_matrix_3_V_address1),
    .matrix_3_V_ce1(mvprod_layer_1_U0_matrix_3_V_ce1),
    .matrix_3_V_q1(weights_L1_3_V_q1),
    .matrix_4_V_address0(mvprod_layer_1_U0_matrix_4_V_address0),
    .matrix_4_V_ce0(mvprod_layer_1_U0_matrix_4_V_ce0),
    .matrix_4_V_q0(weights_L1_4_V_q0),
    .matrix_4_V_address1(mvprod_layer_1_U0_matrix_4_V_address1),
    .matrix_4_V_ce1(mvprod_layer_1_U0_matrix_4_V_ce1),
    .matrix_4_V_q1(weights_L1_4_V_q1),
    .matrix_5_V_address0(mvprod_layer_1_U0_matrix_5_V_address0),
    .matrix_5_V_ce0(mvprod_layer_1_U0_matrix_5_V_ce0),
    .matrix_5_V_q0(weights_L1_5_V_q0),
    .matrix_5_V_address1(mvprod_layer_1_U0_matrix_5_V_address1),
    .matrix_5_V_ce1(mvprod_layer_1_U0_matrix_5_V_ce1),
    .matrix_5_V_q1(weights_L1_5_V_q1),
    .matrix_6_V_address0(mvprod_layer_1_U0_matrix_6_V_address0),
    .matrix_6_V_ce0(mvprod_layer_1_U0_matrix_6_V_ce0),
    .matrix_6_V_q0(weights_L1_6_V_q0),
    .matrix_6_V_address1(mvprod_layer_1_U0_matrix_6_V_address1),
    .matrix_6_V_ce1(mvprod_layer_1_U0_matrix_6_V_ce1),
    .matrix_6_V_q1(weights_L1_6_V_q1),
    .matrix_7_V_address0(mvprod_layer_1_U0_matrix_7_V_address0),
    .matrix_7_V_ce0(mvprod_layer_1_U0_matrix_7_V_ce0),
    .matrix_7_V_q0(weights_L1_7_V_q0),
    .matrix_7_V_address1(mvprod_layer_1_U0_matrix_7_V_address1),
    .matrix_7_V_ce1(mvprod_layer_1_U0_matrix_7_V_ce1),
    .matrix_7_V_q1(weights_L1_7_V_q1),
    .input_0_V_address0(mvprod_layer_1_U0_input_0_V_address0),
    .input_0_V_ce0(mvprod_layer_1_U0_input_0_V_ce0),
    .input_0_V_q0(bias_added_0_V_t_q0),
    .input_0_V_address1(mvprod_layer_1_U0_input_0_V_address1),
    .input_0_V_ce1(mvprod_layer_1_U0_input_0_V_ce1),
    .input_0_V_q1(bias_added_0_V_t_q1),
    .input_1_V_address0(mvprod_layer_1_U0_input_1_V_address0),
    .input_1_V_ce0(mvprod_layer_1_U0_input_1_V_ce0),
    .input_1_V_q0(bias_added_1_V_t_q0),
    .input_1_V_address1(mvprod_layer_1_U0_input_1_V_address1),
    .input_1_V_ce1(mvprod_layer_1_U0_input_1_V_ce1),
    .input_1_V_q1(bias_added_1_V_t_q1),
    .input_2_V_address0(mvprod_layer_1_U0_input_2_V_address0),
    .input_2_V_ce0(mvprod_layer_1_U0_input_2_V_ce0),
    .input_2_V_q0(bias_added_2_V_t_q0),
    .input_2_V_address1(mvprod_layer_1_U0_input_2_V_address1),
    .input_2_V_ce1(mvprod_layer_1_U0_input_2_V_ce1),
    .input_2_V_q1(bias_added_2_V_t_q1),
    .input_3_V_address0(mvprod_layer_1_U0_input_3_V_address0),
    .input_3_V_ce0(mvprod_layer_1_U0_input_3_V_ce0),
    .input_3_V_q0(bias_added_3_V_t_q0),
    .input_3_V_address1(mvprod_layer_1_U0_input_3_V_address1),
    .input_3_V_ce1(mvprod_layer_1_U0_input_3_V_ce1),
    .input_3_V_q1(bias_added_3_V_t_q1),
    .input_4_V_address0(mvprod_layer_1_U0_input_4_V_address0),
    .input_4_V_ce0(mvprod_layer_1_U0_input_4_V_ce0),
    .input_4_V_q0(bias_added_4_V_t_q0),
    .input_4_V_address1(mvprod_layer_1_U0_input_4_V_address1),
    .input_4_V_ce1(mvprod_layer_1_U0_input_4_V_ce1),
    .input_4_V_q1(bias_added_4_V_t_q1),
    .input_5_V_address0(mvprod_layer_1_U0_input_5_V_address0),
    .input_5_V_ce0(mvprod_layer_1_U0_input_5_V_ce0),
    .input_5_V_q0(bias_added_5_V_t_q0),
    .input_5_V_address1(mvprod_layer_1_U0_input_5_V_address1),
    .input_5_V_ce1(mvprod_layer_1_U0_input_5_V_ce1),
    .input_5_V_q1(bias_added_5_V_t_q1),
    .input_6_V_address0(mvprod_layer_1_U0_input_6_V_address0),
    .input_6_V_ce0(mvprod_layer_1_U0_input_6_V_ce0),
    .input_6_V_q0(bias_added_6_V_t_q0),
    .input_6_V_address1(mvprod_layer_1_U0_input_6_V_address1),
    .input_6_V_ce1(mvprod_layer_1_U0_input_6_V_ce1),
    .input_6_V_q1(bias_added_6_V_t_q1),
    .input_7_V_address0(mvprod_layer_1_U0_input_7_V_address0),
    .input_7_V_ce0(mvprod_layer_1_U0_input_7_V_ce0),
    .input_7_V_q0(bias_added_7_V_t_q0),
    .input_7_V_address1(mvprod_layer_1_U0_input_7_V_address1),
    .input_7_V_ce1(mvprod_layer_1_U0_input_7_V_ce1),
    .input_7_V_q1(bias_added_7_V_t_q1),
    .result_V_address0(mvprod_layer_1_U0_result_V_address0),
    .result_V_ce0(mvprod_layer_1_U0_result_V_ce0),
    .result_V_we0(mvprod_layer_1_U0_result_V_we0),
    .result_V_d0(mvprod_layer_1_U0_result_V_d0)
);

sigmoid_activation_L_1 sigmoid_activation_L_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sigmoid_activation_L_1_U0_ap_start),
    .ap_done(sigmoid_activation_L_1_U0_ap_done),
    .ap_continue(sigmoid_activation_L_1_U0_ap_continue),
    .ap_idle(sigmoid_activation_L_1_U0_ap_idle),
    .ap_ready(sigmoid_activation_L_1_U0_ap_ready),
    .input_V_address0(sigmoid_activation_L_1_U0_input_V_address0),
    .input_V_ce0(sigmoid_activation_L_1_U0_input_V_ce0),
    .input_V_q0(L1_no_activ_V_t_q0),
    .result_V_address0(sigmoid_activation_L_1_U0_result_V_address0),
    .result_V_ce0(sigmoid_activation_L_1_U0_result_V_ce0),
    .result_V_we0(sigmoid_activation_L_1_U0_result_V_we0),
    .result_V_d0(sigmoid_activation_L_1_U0_result_V_d0)
);

add_bias_pre_L2 add_bias_pre_L2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(add_bias_pre_L2_U0_ap_start),
    .ap_done(add_bias_pre_L2_U0_ap_done),
    .ap_continue(add_bias_pre_L2_U0_ap_continue),
    .ap_idle(add_bias_pre_L2_U0_ap_idle),
    .ap_ready(add_bias_pre_L2_U0_ap_ready),
    .input_V_address0(add_bias_pre_L2_U0_input_V_address0),
    .input_V_ce0(add_bias_pre_L2_U0_input_V_ce0),
    .input_V_q0(L1_activ_V_t_q0),
    .result_V_address0(add_bias_pre_L2_U0_result_V_address0),
    .result_V_ce0(add_bias_pre_L2_U0_result_V_ce0),
    .result_V_we0(add_bias_pre_L2_U0_result_V_we0),
    .result_V_d0(add_bias_pre_L2_U0_result_V_d0)
);

mvprod_layer_2 mvprod_layer_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(mvprod_layer_2_U0_ap_start),
    .ap_done(mvprod_layer_2_U0_ap_done),
    .ap_continue(mvprod_layer_2_U0_ap_continue),
    .ap_idle(mvprod_layer_2_U0_ap_idle),
    .ap_ready(mvprod_layer_2_U0_ap_ready),
    .matrix_V_address0(mvprod_layer_2_U0_matrix_V_address0),
    .matrix_V_ce0(mvprod_layer_2_U0_matrix_V_ce0),
    .matrix_V_q0(weights_L2_V_q0),
    .matrix_V_address1(mvprod_layer_2_U0_matrix_V_address1),
    .matrix_V_ce1(mvprod_layer_2_U0_matrix_V_ce1),
    .matrix_V_q1(weights_L2_V_q1),
    .input_V_address0(mvprod_layer_2_U0_input_V_address0),
    .input_V_ce0(mvprod_layer_2_U0_input_V_ce0),
    .input_V_q0(L2_bias_added_V_t_q0),
    .input_V_address1(mvprod_layer_2_U0_input_V_address1),
    .input_V_ce1(mvprod_layer_2_U0_input_V_ce1),
    .input_V_q1(L2_bias_added_V_t_q1),
    .result_V_address0(mvprod_layer_2_U0_result_V_address0),
    .result_V_ce0(mvprod_layer_2_U0_result_V_ce0),
    .result_V_we0(mvprod_layer_2_U0_result_V_we0),
    .result_V_d0(mvprod_layer_2_U0_result_V_d0)
);

sigmoid_activation_L sigmoid_activation_L_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(sigmoid_activation_L_U0_ap_start),
    .ap_done(sigmoid_activation_L_U0_ap_done),
    .ap_continue(sigmoid_activation_L_U0_ap_continue),
    .ap_idle(sigmoid_activation_L_U0_ap_idle),
    .ap_ready(sigmoid_activation_L_U0_ap_ready),
    .input_V_address0(sigmoid_activation_L_U0_input_V_address0),
    .input_V_ce0(sigmoid_activation_L_U0_input_V_ce0),
    .input_V_q0(L2_out_V_t_q0),
    .result_V_address0(sigmoid_activation_L_U0_result_V_address0),
    .result_V_ce0(sigmoid_activation_L_U0_result_V_ce0),
    .result_V_we0(sigmoid_activation_L_U0_result_V_we0),
    .result_V_d0(sigmoid_activation_L_U0_result_V_d0)
);

classify classify_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(classify_U0_ap_start),
    .ap_done(classify_U0_ap_done),
    .ap_continue(classify_U0_ap_continue),
    .ap_idle(classify_U0_ap_idle),
    .ap_ready(classify_U0_ap_ready),
    .activated_L2_V_address0(classify_U0_activated_L2_V_address0),
    .activated_L2_V_ce0(classify_U0_activated_L2_V_ce0),
    .activated_L2_V_q0(L2_out_activ_V_t_q0),
    .ap_return(classify_U0_ap_return)
);

Block_arrayctor_loop Block_arrayctor_loop_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_arrayctor_loop_U0_ap_start),
    .ap_done(Block_arrayctor_loop_U0_ap_done),
    .ap_continue(Block_arrayctor_loop_U0_ap_continue),
    .ap_idle(Block_arrayctor_loop_U0_ap_idle),
    .ap_ready(Block_arrayctor_loop_U0_ap_ready),
    .p_read(digit_dout),
    .ap_return(Block_arrayctor_loop_U0_ap_return)
);

p_src_mlp_cpp_lin p_src_mlp_cpp_lin_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_src_mlp_cpp_lin_U0_ap_start),
    .ap_done(p_src_mlp_cpp_lin_U0_ap_done),
    .ap_continue(p_src_mlp_cpp_lin_U0_ap_continue),
    .ap_idle(p_src_mlp_cpp_lin_U0_ap_idle),
    .ap_ready(p_src_mlp_cpp_lin_U0_ap_ready),
    .p_read(digit_load_loc_chann_dout),
    .ap_return(p_src_mlp_cpp_lin_U0_ap_return)
);

fifo_w32_d2_A digit_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(classify_U0_ap_return),
    .if_full_n(digit_full_n),
    .if_write(classify_U0_ap_done),
    .if_dout(digit_dout),
    .if_empty_n(digit_empty_n),
    .if_read(Block_arrayctor_loop_U0_ap_ready)
);

fifo_w32_d2_A digit_load_loc_chann_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_arrayctor_loop_U0_ap_return),
    .if_full_n(digit_load_loc_chann_full_n),
    .if_write(Block_arrayctor_loop_U0_ap_done),
    .if_dout(digit_load_loc_chann_dout),
    .if_empty_n(digit_load_loc_chann_empty_n),
    .if_read(p_src_mlp_cpp_lin_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_add_bias_pre_L1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_add_bias_pre_L1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_add_bias_pre_L1_U0_ap_ready <= ap_sync_add_bias_pre_L1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_0_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_0_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_0_V <= ap_sync_channel_write_bias_added_0_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_1_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_1_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_1_V <= ap_sync_channel_write_bias_added_1_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_2_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_2_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_2_V <= ap_sync_channel_write_bias_added_2_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_3_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_3_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_3_V <= ap_sync_channel_write_bias_added_3_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_4_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_4_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_4_V <= ap_sync_channel_write_bias_added_4_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_5_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_5_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_5_V <= ap_sync_channel_write_bias_added_5_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_6_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_6_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_6_V <= ap_sync_channel_write_bias_added_6_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bias_added_7_V <= 1'b0;
    end else begin
        if (((add_bias_pre_L1_U0_ap_done & add_bias_pre_L1_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bias_added_7_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bias_added_7_V <= ap_sync_channel_write_bias_added_7_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_mvprod_layer_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_mvprod_layer_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_mvprod_layer_1_U0_ap_ready <= ap_sync_mvprod_layer_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_mvprod_layer_2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_mvprod_layer_2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_mvprod_layer_2_U0_ap_ready <= ap_sync_mvprod_layer_2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == add_bias_pre_L1_U0_ap_ready) & (ap_sync_ready == 1'b1))) begin
        add_bias_pre_L1_U0_ap_ready_count <= (add_bias_pre_L1_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == add_bias_pre_L1_U0_ap_ready))) begin
        add_bias_pre_L1_U0_ap_ready_count <= (add_bias_pre_L1_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((mvprod_layer_1_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        mvprod_layer_1_U0_ap_ready_count <= (mvprod_layer_1_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (mvprod_layer_1_U0_ap_ready == 1'b1))) begin
        mvprod_layer_1_U0_ap_ready_count <= (mvprod_layer_1_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((mvprod_layer_2_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        mvprod_layer_2_U0_ap_ready_count <= (mvprod_layer_2_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (mvprod_layer_2_U0_ap_ready == 1'b1))) begin
        mvprod_layer_2_U0_ap_ready_count <= (mvprod_layer_2_U0_ap_ready_count + 2'd1);
    end
end

assign Block_arrayctor_loop_U0_ap_continue = digit_load_loc_chann_full_n;

assign Block_arrayctor_loop_U0_ap_start = digit_empty_n;

assign Block_arrayctor_loop_U0_start_full_n = 1'b1;

assign Block_arrayctor_loop_U0_start_write = 1'b0;

assign L2_bias_added_V_t_d1 = 18'd0;

assign L2_bias_added_V_t_we1 = 1'b0;

assign add_bias_pre_L1_U0_ap_continue = (ap_sync_channel_write_bias_added_7_V & ap_sync_channel_write_bias_added_6_V & ap_sync_channel_write_bias_added_5_V & ap_sync_channel_write_bias_added_4_V & ap_sync_channel_write_bias_added_3_V & ap_sync_channel_write_bias_added_2_V & ap_sync_channel_write_bias_added_1_V & ap_sync_channel_write_bias_added_0_V);

assign add_bias_pre_L1_U0_ap_start = ((ap_sync_reg_add_bias_pre_L1_U0_ap_ready ^ 1'b1) & ap_start);

assign add_bias_pre_L1_U0_result_0_V_full_n = bias_added_0_V_i_full_n;

assign add_bias_pre_L1_U0_result_1_V_full_n = bias_added_1_V_i_full_n;

assign add_bias_pre_L1_U0_result_2_V_full_n = bias_added_2_V_i_full_n;

assign add_bias_pre_L1_U0_result_3_V_full_n = bias_added_3_V_i_full_n;

assign add_bias_pre_L1_U0_result_4_V_full_n = bias_added_4_V_i_full_n;

assign add_bias_pre_L1_U0_result_5_V_full_n = bias_added_5_V_i_full_n;

assign add_bias_pre_L1_U0_result_6_V_full_n = bias_added_6_V_i_full_n;

assign add_bias_pre_L1_U0_result_7_V_full_n = bias_added_7_V_i_full_n;

assign add_bias_pre_L1_U0_start_full_n = 1'b1;

assign add_bias_pre_L1_U0_start_write = 1'b0;

assign add_bias_pre_L2_U0_ap_continue = L2_bias_added_V_i_full_n;

assign add_bias_pre_L2_U0_ap_start = L1_activ_V_t_empty_n;

assign add_bias_pre_L2_U0_result_V_full_n = L2_bias_added_V_i_full_n;

assign add_bias_pre_L2_U0_start_full_n = 1'b1;

assign add_bias_pre_L2_U0_start_write = 1'b0;

assign ap_channel_done_L1_activ_V = sigmoid_activation_L_1_U0_ap_done;

assign ap_channel_done_L1_no_activ_V = mvprod_layer_1_U0_ap_done;

assign ap_channel_done_L2_bias_added_V = add_bias_pre_L2_U0_ap_done;

assign ap_channel_done_L2_out_V = mvprod_layer_2_U0_ap_done;

assign ap_channel_done_L2_out_activ_V = sigmoid_activation_L_U0_ap_done;

assign ap_channel_done_bias_added_0_V = ((ap_sync_reg_channel_write_bias_added_0_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_bias_added_1_V = ((ap_sync_reg_channel_write_bias_added_1_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_bias_added_2_V = ((ap_sync_reg_channel_write_bias_added_2_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_bias_added_3_V = ((ap_sync_reg_channel_write_bias_added_3_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_bias_added_4_V = ((ap_sync_reg_channel_write_bias_added_4_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_bias_added_5_V = ((ap_sync_reg_channel_write_bias_added_5_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_bias_added_6_V = ((ap_sync_reg_channel_write_bias_added_6_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_bias_added_7_V = ((ap_sync_reg_channel_write_bias_added_7_V ^ 1'b1) & add_bias_pre_L1_U0_ap_done);

assign ap_channel_done_digit = classify_U0_ap_done;

assign ap_channel_done_digit_load_loc_chann = Block_arrayctor_loop_U0_ap_done;

assign ap_done = p_src_mlp_cpp_lin_U0_ap_done;

assign ap_idle = (sigmoid_activation_L_U0_ap_idle & sigmoid_activation_L_1_U0_ap_idle & p_src_mlp_cpp_lin_U0_ap_idle & mvprod_layer_2_U0_ap_idle & mvprod_layer_1_U0_ap_idle & (digit_load_loc_chann_empty_n ^ 1'b1) & (digit_empty_n ^ 1'b1) & (1'b1 ^ L2_out_activ_V_t_empty_n) & (1'b1 ^ L2_out_V_t_empty_n) & (1'b1 ^ L2_bias_added_V_t_empty_n) & (1'b1 ^ L1_activ_V_t_empty_n) & (1'b1 ^ L1_no_activ_V_t_empty_n) & (bias_added_7_V_t_empty_n ^ 1'b1) & (bias_added_6_V_t_empty_n ^ 1'b1) & (bias_added_5_V_t_empty_n ^ 1'b1) & (bias_added_4_V_t_empty_n ^ 1'b1) & (bias_added_3_V_t_empty_n ^ 1'b1) & (bias_added_2_V_t_empty_n ^ 1'b1) & (bias_added_1_V_t_empty_n ^ 1'b1) & (bias_added_0_V_t_empty_n ^ 1'b1) & classify_U0_ap_idle & add_bias_pre_L2_U0_ap_idle & add_bias_pre_L1_U0_ap_idle & Block_arrayctor_loop_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_return = p_src_mlp_cpp_lin_U0_ap_return;

assign ap_sync_add_bias_pre_L1_U0_ap_ready = (ap_sync_reg_add_bias_pre_L1_U0_ap_ready | add_bias_pre_L1_U0_ap_ready);

assign ap_sync_channel_write_bias_added_0_V = ((ap_channel_done_bias_added_0_V & add_bias_pre_L1_U0_result_0_V_full_n) | ap_sync_reg_channel_write_bias_added_0_V);

assign ap_sync_channel_write_bias_added_1_V = ((ap_channel_done_bias_added_1_V & add_bias_pre_L1_U0_result_1_V_full_n) | ap_sync_reg_channel_write_bias_added_1_V);

assign ap_sync_channel_write_bias_added_2_V = ((ap_channel_done_bias_added_2_V & add_bias_pre_L1_U0_result_2_V_full_n) | ap_sync_reg_channel_write_bias_added_2_V);

assign ap_sync_channel_write_bias_added_3_V = ((ap_channel_done_bias_added_3_V & add_bias_pre_L1_U0_result_3_V_full_n) | ap_sync_reg_channel_write_bias_added_3_V);

assign ap_sync_channel_write_bias_added_4_V = ((ap_channel_done_bias_added_4_V & add_bias_pre_L1_U0_result_4_V_full_n) | ap_sync_reg_channel_write_bias_added_4_V);

assign ap_sync_channel_write_bias_added_5_V = ((ap_channel_done_bias_added_5_V & add_bias_pre_L1_U0_result_5_V_full_n) | ap_sync_reg_channel_write_bias_added_5_V);

assign ap_sync_channel_write_bias_added_6_V = ((ap_channel_done_bias_added_6_V & add_bias_pre_L1_U0_result_6_V_full_n) | ap_sync_reg_channel_write_bias_added_6_V);

assign ap_sync_channel_write_bias_added_7_V = ((ap_channel_done_bias_added_7_V & add_bias_pre_L1_U0_result_7_V_full_n) | ap_sync_reg_channel_write_bias_added_7_V);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = p_src_mlp_cpp_lin_U0_ap_done;

assign ap_sync_mvprod_layer_1_U0_ap_ready = (mvprod_layer_1_U0_ap_ready | ap_sync_reg_mvprod_layer_1_U0_ap_ready);

assign ap_sync_mvprod_layer_2_U0_ap_ready = (mvprod_layer_2_U0_ap_ready | ap_sync_reg_mvprod_layer_2_U0_ap_ready);

assign ap_sync_ready = (ap_sync_mvprod_layer_2_U0_ap_ready & ap_sync_mvprod_layer_1_U0_ap_ready & ap_sync_add_bias_pre_L1_U0_ap_ready);

assign bias_added_0_V_t_d1 = 18'd0;

assign bias_added_0_V_t_we1 = 1'b0;

assign bias_added_1_V_t_d1 = 18'd0;

assign bias_added_1_V_t_we1 = 1'b0;

assign bias_added_2_V_t_d1 = 18'd0;

assign bias_added_2_V_t_we1 = 1'b0;

assign bias_added_3_V_t_d1 = 18'd0;

assign bias_added_3_V_t_we1 = 1'b0;

assign bias_added_4_V_t_d1 = 18'd0;

assign bias_added_4_V_t_we1 = 1'b0;

assign bias_added_5_V_t_d1 = 18'd0;

assign bias_added_5_V_t_we1 = 1'b0;

assign bias_added_6_V_t_d1 = 18'd0;

assign bias_added_6_V_t_we1 = 1'b0;

assign bias_added_7_V_t_d1 = 18'd0;

assign bias_added_7_V_t_we1 = 1'b0;

assign classify_U0_ap_continue = digit_full_n;

assign classify_U0_ap_start = L2_out_activ_V_t_empty_n;

assign classify_U0_start_full_n = 1'b1;

assign classify_U0_start_write = 1'b0;

assign input_0_V_address0 = add_bias_pre_L1_U0_input_0_V_address0;

assign input_0_V_address1 = 6'd0;

assign input_0_V_ce0 = add_bias_pre_L1_U0_input_0_V_ce0;

assign input_0_V_ce1 = 1'b0;

assign input_0_V_d0 = 18'd0;

assign input_0_V_d1 = 18'd0;

assign input_0_V_we0 = 1'b0;

assign input_0_V_we1 = 1'b0;

assign input_1_V_address0 = add_bias_pre_L1_U0_input_1_V_address0;

assign input_1_V_address1 = 6'd0;

assign input_1_V_ce0 = add_bias_pre_L1_U0_input_1_V_ce0;

assign input_1_V_ce1 = 1'b0;

assign input_1_V_d0 = 18'd0;

assign input_1_V_d1 = 18'd0;

assign input_1_V_we0 = 1'b0;

assign input_1_V_we1 = 1'b0;

assign input_2_V_address0 = add_bias_pre_L1_U0_input_2_V_address0;

assign input_2_V_address1 = 6'd0;

assign input_2_V_ce0 = add_bias_pre_L1_U0_input_2_V_ce0;

assign input_2_V_ce1 = 1'b0;

assign input_2_V_d0 = 18'd0;

assign input_2_V_d1 = 18'd0;

assign input_2_V_we0 = 1'b0;

assign input_2_V_we1 = 1'b0;

assign input_3_V_address0 = add_bias_pre_L1_U0_input_3_V_address0;

assign input_3_V_address1 = 6'd0;

assign input_3_V_ce0 = add_bias_pre_L1_U0_input_3_V_ce0;

assign input_3_V_ce1 = 1'b0;

assign input_3_V_d0 = 18'd0;

assign input_3_V_d1 = 18'd0;

assign input_3_V_we0 = 1'b0;

assign input_3_V_we1 = 1'b0;

assign input_4_V_address0 = add_bias_pre_L1_U0_input_4_V_address0;

assign input_4_V_address1 = 6'd0;

assign input_4_V_ce0 = add_bias_pre_L1_U0_input_4_V_ce0;

assign input_4_V_ce1 = 1'b0;

assign input_4_V_d0 = 18'd0;

assign input_4_V_d1 = 18'd0;

assign input_4_V_we0 = 1'b0;

assign input_4_V_we1 = 1'b0;

assign input_5_V_address0 = add_bias_pre_L1_U0_input_5_V_address0;

assign input_5_V_address1 = 6'd0;

assign input_5_V_ce0 = add_bias_pre_L1_U0_input_5_V_ce0;

assign input_5_V_ce1 = 1'b0;

assign input_5_V_d0 = 18'd0;

assign input_5_V_d1 = 18'd0;

assign input_5_V_we0 = 1'b0;

assign input_5_V_we1 = 1'b0;

assign input_6_V_address0 = add_bias_pre_L1_U0_input_6_V_address0;

assign input_6_V_address1 = 6'd0;

assign input_6_V_ce0 = add_bias_pre_L1_U0_input_6_V_ce0;

assign input_6_V_ce1 = 1'b0;

assign input_6_V_d0 = 18'd0;

assign input_6_V_d1 = 18'd0;

assign input_6_V_we0 = 1'b0;

assign input_6_V_we1 = 1'b0;

assign input_7_V_address0 = add_bias_pre_L1_U0_input_7_V_address0;

assign input_7_V_address1 = 6'd0;

assign input_7_V_ce0 = add_bias_pre_L1_U0_input_7_V_ce0;

assign input_7_V_ce1 = 1'b0;

assign input_7_V_d0 = 18'd0;

assign input_7_V_d1 = 18'd0;

assign input_7_V_we0 = 1'b0;

assign input_7_V_we1 = 1'b0;

assign mvprod_layer_1_U0_ap_continue = L1_no_activ_V_i_full_n;

assign mvprod_layer_1_U0_ap_start = ((ap_sync_reg_mvprod_layer_1_U0_ap_ready ^ 1'b1) & bias_added_7_V_t_empty_n & bias_added_6_V_t_empty_n & bias_added_5_V_t_empty_n & bias_added_4_V_t_empty_n & bias_added_3_V_t_empty_n & bias_added_2_V_t_empty_n & bias_added_1_V_t_empty_n & bias_added_0_V_t_empty_n & ap_start);

assign mvprod_layer_1_U0_result_V_full_n = L1_no_activ_V_i_full_n;

assign mvprod_layer_1_U0_start_full_n = 1'b1;

assign mvprod_layer_1_U0_start_write = 1'b0;

assign mvprod_layer_2_U0_ap_continue = L2_out_V_i_full_n;

assign mvprod_layer_2_U0_ap_start = ((ap_sync_reg_mvprod_layer_2_U0_ap_ready ^ 1'b1) & ap_start & L2_bias_added_V_t_empty_n);

assign mvprod_layer_2_U0_result_V_full_n = L2_out_V_i_full_n;

assign mvprod_layer_2_U0_start_full_n = 1'b1;

assign mvprod_layer_2_U0_start_write = 1'b0;

assign p_src_mlp_cpp_lin_U0_ap_continue = 1'b1;

assign p_src_mlp_cpp_lin_U0_ap_start = digit_load_loc_chann_empty_n;

assign p_src_mlp_cpp_lin_U0_start_full_n = 1'b1;

assign p_src_mlp_cpp_lin_U0_start_write = 1'b0;

assign sigmoid_activation_L_1_U0_ap_continue = L1_activ_V_i_full_n;

assign sigmoid_activation_L_1_U0_ap_start = L1_no_activ_V_t_empty_n;

assign sigmoid_activation_L_1_U0_result_V_full_n = L1_activ_V_i_full_n;

assign sigmoid_activation_L_1_U0_start_full_n = 1'b1;

assign sigmoid_activation_L_1_U0_start_write = 1'b0;

assign sigmoid_activation_L_U0_ap_continue = L2_out_activ_V_i_full_n;

assign sigmoid_activation_L_U0_ap_start = L2_out_V_t_empty_n;

assign sigmoid_activation_L_U0_result_V_full_n = L2_out_activ_V_i_full_n;

assign sigmoid_activation_L_U0_start_full_n = 1'b1;

assign sigmoid_activation_L_U0_start_write = 1'b0;

assign tmp_p_src_mlp_cpp_lin_fu_222_ap_return = 32'd0;

assign weights_L1_0_V_address0 = mvprod_layer_1_U0_matrix_0_V_address0;

assign weights_L1_0_V_address1 = mvprod_layer_1_U0_matrix_0_V_address1;

assign weights_L1_0_V_ce0 = mvprod_layer_1_U0_matrix_0_V_ce0;

assign weights_L1_0_V_ce1 = mvprod_layer_1_U0_matrix_0_V_ce1;

assign weights_L1_0_V_d0 = 18'd0;

assign weights_L1_0_V_d1 = 18'd0;

assign weights_L1_0_V_we0 = 1'b0;

assign weights_L1_0_V_we1 = 1'b0;

assign weights_L1_1_V_address0 = mvprod_layer_1_U0_matrix_1_V_address0;

assign weights_L1_1_V_address1 = mvprod_layer_1_U0_matrix_1_V_address1;

assign weights_L1_1_V_ce0 = mvprod_layer_1_U0_matrix_1_V_ce0;

assign weights_L1_1_V_ce1 = mvprod_layer_1_U0_matrix_1_V_ce1;

assign weights_L1_1_V_d0 = 18'd0;

assign weights_L1_1_V_d1 = 18'd0;

assign weights_L1_1_V_we0 = 1'b0;

assign weights_L1_1_V_we1 = 1'b0;

assign weights_L1_2_V_address0 = mvprod_layer_1_U0_matrix_2_V_address0;

assign weights_L1_2_V_address1 = mvprod_layer_1_U0_matrix_2_V_address1;

assign weights_L1_2_V_ce0 = mvprod_layer_1_U0_matrix_2_V_ce0;

assign weights_L1_2_V_ce1 = mvprod_layer_1_U0_matrix_2_V_ce1;

assign weights_L1_2_V_d0 = 18'd0;

assign weights_L1_2_V_d1 = 18'd0;

assign weights_L1_2_V_we0 = 1'b0;

assign weights_L1_2_V_we1 = 1'b0;

assign weights_L1_3_V_address0 = mvprod_layer_1_U0_matrix_3_V_address0;

assign weights_L1_3_V_address1 = mvprod_layer_1_U0_matrix_3_V_address1;

assign weights_L1_3_V_ce0 = mvprod_layer_1_U0_matrix_3_V_ce0;

assign weights_L1_3_V_ce1 = mvprod_layer_1_U0_matrix_3_V_ce1;

assign weights_L1_3_V_d0 = 18'd0;

assign weights_L1_3_V_d1 = 18'd0;

assign weights_L1_3_V_we0 = 1'b0;

assign weights_L1_3_V_we1 = 1'b0;

assign weights_L1_4_V_address0 = mvprod_layer_1_U0_matrix_4_V_address0;

assign weights_L1_4_V_address1 = mvprod_layer_1_U0_matrix_4_V_address1;

assign weights_L1_4_V_ce0 = mvprod_layer_1_U0_matrix_4_V_ce0;

assign weights_L1_4_V_ce1 = mvprod_layer_1_U0_matrix_4_V_ce1;

assign weights_L1_4_V_d0 = 18'd0;

assign weights_L1_4_V_d1 = 18'd0;

assign weights_L1_4_V_we0 = 1'b0;

assign weights_L1_4_V_we1 = 1'b0;

assign weights_L1_5_V_address0 = mvprod_layer_1_U0_matrix_5_V_address0;

assign weights_L1_5_V_address1 = mvprod_layer_1_U0_matrix_5_V_address1;

assign weights_L1_5_V_ce0 = mvprod_layer_1_U0_matrix_5_V_ce0;

assign weights_L1_5_V_ce1 = mvprod_layer_1_U0_matrix_5_V_ce1;

assign weights_L1_5_V_d0 = 18'd0;

assign weights_L1_5_V_d1 = 18'd0;

assign weights_L1_5_V_we0 = 1'b0;

assign weights_L1_5_V_we1 = 1'b0;

assign weights_L1_6_V_address0 = mvprod_layer_1_U0_matrix_6_V_address0;

assign weights_L1_6_V_address1 = mvprod_layer_1_U0_matrix_6_V_address1;

assign weights_L1_6_V_ce0 = mvprod_layer_1_U0_matrix_6_V_ce0;

assign weights_L1_6_V_ce1 = mvprod_layer_1_U0_matrix_6_V_ce1;

assign weights_L1_6_V_d0 = 18'd0;

assign weights_L1_6_V_d1 = 18'd0;

assign weights_L1_6_V_we0 = 1'b0;

assign weights_L1_6_V_we1 = 1'b0;

assign weights_L1_7_V_address0 = mvprod_layer_1_U0_matrix_7_V_address0;

assign weights_L1_7_V_address1 = mvprod_layer_1_U0_matrix_7_V_address1;

assign weights_L1_7_V_ce0 = mvprod_layer_1_U0_matrix_7_V_ce0;

assign weights_L1_7_V_ce1 = mvprod_layer_1_U0_matrix_7_V_ce1;

assign weights_L1_7_V_d0 = 18'd0;

assign weights_L1_7_V_d1 = 18'd0;

assign weights_L1_7_V_we0 = 1'b0;

assign weights_L1_7_V_we1 = 1'b0;

assign weights_L2_V_address0 = mvprod_layer_2_U0_matrix_V_address0;

assign weights_L2_V_address1 = mvprod_layer_2_U0_matrix_V_address1;

assign weights_L2_V_ce0 = mvprod_layer_2_U0_matrix_V_ce0;

assign weights_L2_V_ce1 = mvprod_layer_2_U0_matrix_V_ce1;

assign weights_L2_V_d0 = 18'd0;

assign weights_L2_V_d1 = 18'd0;

assign weights_L2_V_we0 = 1'b0;

assign weights_L2_V_we1 = 1'b0;

endmodule //mlp
