// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "add_bias_pre_L1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic add_bias_pre_L1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic add_bias_pre_L1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> add_bias_pre_L1::ap_ST_fsm_state1 = "1";
const sc_lv<4> add_bias_pre_L1::ap_ST_fsm_state2 = "10";
const sc_lv<4> add_bias_pre_L1::ap_ST_fsm_state3 = "100";
const sc_lv<4> add_bias_pre_L1::ap_ST_fsm_state4 = "1000";
const sc_lv<32> add_bias_pre_L1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> add_bias_pre_L1::ap_const_lv32_1 = "1";
const sc_lv<32> add_bias_pre_L1::ap_const_lv32_2 = "10";
const sc_lv<9> add_bias_pre_L1::ap_const_lv9_0 = "000000000";
const sc_lv<32> add_bias_pre_L1::ap_const_lv32_3 = "11";
const sc_lv<64> add_bias_pre_L1::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<18> add_bias_pre_L1::ap_const_lv18_10000 = "10000000000000000";
const sc_lv<9> add_bias_pre_L1::ap_const_lv9_190 = "110010000";
const sc_lv<9> add_bias_pre_L1::ap_const_lv9_1 = "1";
const sc_lv<1> add_bias_pre_L1::ap_const_lv1_1 = "1";
const bool add_bias_pre_L1::ap_const_boolean_1 = true;

add_bias_pre_L1::add_bias_pre_L1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_69_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_69_p2 );

    SC_METHOD(thread_i_3_fu_75_p2);
    sensitive << ( i_reg_58 );

    SC_METHOD(thread_input_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_18_fu_81_p1 );

    SC_METHOD(thread_input_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_result_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_s_fu_86_p1 );

    SC_METHOD(thread_result_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_result_V_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( input_V_load_reg_104 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_result_V_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_tmp_18_fu_81_p1);
    sensitive << ( i_reg_58 );

    SC_METHOD(thread_tmp_fu_69_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_58 );

    SC_METHOD(thread_tmp_s_fu_86_p1);
    sensitive << ( i_3_reg_93 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_69_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "add_bias_pre_L1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_V_address0, "(port)input_V_address0");
    sc_trace(mVcdFile, input_V_ce0, "(port)input_V_ce0");
    sc_trace(mVcdFile, input_V_q0, "(port)input_V_q0");
    sc_trace(mVcdFile, result_V_address0, "(port)result_V_address0");
    sc_trace(mVcdFile, result_V_ce0, "(port)result_V_ce0");
    sc_trace(mVcdFile, result_V_we0, "(port)result_V_we0");
    sc_trace(mVcdFile, result_V_d0, "(port)result_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_3_fu_75_p2, "i_3_fu_75_p2");
    sc_trace(mVcdFile, i_3_reg_93, "i_3_reg_93");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_fu_69_p2, "tmp_fu_69_p2");
    sc_trace(mVcdFile, input_V_load_reg_104, "input_V_load_reg_104");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_reg_58, "i_reg_58");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_18_fu_81_p1, "tmp_18_fu_81_p1");
    sc_trace(mVcdFile, tmp_s_fu_86_p1, "tmp_s_fu_86_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

add_bias_pre_L1::~add_bias_pre_L1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void add_bias_pre_L1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(tmp_fu_69_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_reg_58 = i_3_reg_93.read();
    } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_reg_58 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_3_reg_93 = i_3_fu_75_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        input_V_load_reg_104 = input_V_q0.read();
    }
}

void add_bias_pre_L1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void add_bias_pre_L1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void add_bias_pre_L1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void add_bias_pre_L1::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void add_bias_pre_L1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void add_bias_pre_L1::thread_ap_done() {
    if ((esl_seteq<1,1,1>(tmp_fu_69_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void add_bias_pre_L1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void add_bias_pre_L1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(tmp_fu_69_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void add_bias_pre_L1::thread_i_3_fu_75_p2() {
    i_3_fu_75_p2 = (!i_reg_58.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_reg_58.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void add_bias_pre_L1::thread_input_V_address0() {
    input_V_address0 =  (sc_lv<9>) (tmp_18_fu_81_p1.read());
}

void add_bias_pre_L1::thread_input_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_V_ce0 = ap_const_logic_1;
    } else {
        input_V_ce0 = ap_const_logic_0;
    }
}

void add_bias_pre_L1::thread_result_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        result_V_address0 =  (sc_lv<9>) (tmp_s_fu_86_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        result_V_address0 =  (sc_lv<9>) (ap_const_lv64_0);
    } else {
        result_V_address0 = "XXXXXXXXX";
    }
}

void add_bias_pre_L1::thread_result_V_ce0() {
    if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        result_V_ce0 = ap_const_logic_1;
    } else {
        result_V_ce0 = ap_const_logic_0;
    }
}

void add_bias_pre_L1::thread_result_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        result_V_d0 = input_V_load_reg_104.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        result_V_d0 = ap_const_lv18_10000;
    } else {
        result_V_d0 =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
    }
}

void add_bias_pre_L1::thread_result_V_we0() {
    if (((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        result_V_we0 = ap_const_logic_1;
    } else {
        result_V_we0 = ap_const_logic_0;
    }
}

void add_bias_pre_L1::thread_tmp_18_fu_81_p1() {
    tmp_18_fu_81_p1 = esl_zext<64,9>(i_reg_58.read());
}

void add_bias_pre_L1::thread_tmp_fu_69_p2() {
    tmp_fu_69_p2 = (!i_reg_58.read().is_01() || !ap_const_lv9_190.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_58.read() == ap_const_lv9_190);
}

void add_bias_pre_L1::thread_tmp_s_fu_86_p1() {
    tmp_s_fu_86_p1 = esl_zext<64,9>(i_3_reg_93.read());
}

void add_bias_pre_L1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(tmp_fu_69_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<4>) ("XXXX");
            break;
    }
}

}

